[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # Use esbuild to bundle functions

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
  port = 8888